Update UntargetablePatch.cs Fixed targetPlayer and Nutcracker
winstxnhdw/lc-hax pull request #245
Opened 2024-01-12 22:02 UTC by Linkis20

https://github.com/winstxnhdw/lc-hax/issues/241
Fixed targetPlayer and Nutcracker

Puffer:
Will see you and create smoke but will not bite you

Girl:
Will haunt you but will not move or be able to kill you

Mask:
Will look at you but can't kill you.

Giant:
Will not see you but can get killed if touched.

I tried to change PufferAI but got errors that playerIsInLOS did not exist
Idk why, PufferAI class has that property...

Also is line 10 !Setting.EnableGodMode needed?

2024-01-12 22:27 UTC, winstxnhdw commented
`Setting.EnableGodMode` prevents infinite Masked spawn when player is grabbed during God mode.

2024-01-13 00:04 UTC, Linkis20 commented
Combined them

2024-01-13 03:13 UTC, winstxnhdw requested changes

2024-01-13 03:13 UTC, winstxnhdw commented on lc-hax/Scripts/Patches/UntargetablePatch.cs
> +[HarmonyPatch()]
You don't need this line.

2024-01-13 11:49 UTC, winstxnhdw approved these changes
Should be all good now.

2024-01-13 11:50 UTC, merged

2024-01-13 16:05 UTC, winstxnhdw commented on lc-hax/Scripts/Patches/UntargetablePatch.cs
> +[HarmonyPatch()]
Okay, I am wrong here.

2024-01-13 21:48 UTC, xAstroBoy commented
I would suggest to remove the !Setting.EnableGodMode and find a better approach to dodge the unlimited masked spawn if you remove demi-god

2024-01-14 03:29 UTC, winstxnhdw commented
Why?

2024-01-14 03:31 UTC, xAstroBoy commented
> Why?

Kinda ruins the game, makes it way too easy and people can easily figure that you are in godmode.

2024-01-14 03:33 UTC, winstxnhdw commented
But you are literally in God mode..

2024-01-14 03:34 UTC, xAstroBoy commented
> But you are literally in God mode..

Yeah but enemies should still target you regardless? Unless ignore is specified

2024-01-14 03:40 UTC, winstxnhdw commented
Okay then should I just bring back `demigod` for this?

2024-01-14 03:44 UTC, xAstroBoy commented
> Okay then should I just bring back `demigod` for this?

Or just remove the !setting.IsGodMode from the condition, i commented it out and even if a masked catches me i dont see any issues here.

2024-01-14 03:46 UTC, winstxnhdw commented
Oh do you not get the infinite masked capture glitch?

2024-01-14 03:48 UTC, xAstroBoy commented
> Oh do you not get the infinite masked capture glitch?

Yep, you can test it out, sure a masked will spawn but you can still dodge it out

2024-01-14 03:49 UTC, winstxnhdw commented
@armorfid since it's no longer a problem in v49, I'll remove it.